str1=input("Enter a string: ")
#main string methods
print("capitalize:",str1.capitalize())
print("count of a",str1.count("a"))
print("center",str1.center(10))
print("isalnum",str1.isalnum())
print("isalpha",str1.isalpha())
print("isdigit",str1.isalpha())
print("upper",str1.upper())
print("lower",str1.lower())
print("length",len(str1))
#string methods
print("1.I'm from {}".format("India"))
print("2.right justify of the string:",str1.rjust(100))
print("3.isprintable:",str1.isprintable())
print("4.position of 'a' in the string using find() method:",str1.find('a'))
print("5.isidentifier:",str1.isidentifier())
print("6.position of 'a' in the string using index() method:",str1.index('a'))
print("7.replacing 'a' with 'e':",str1.replace('a','e'))
print("8.does the string ends with a:",str1.endswith('a'))
print("9.position of last 'a' in the string using find method:",str1.rfind('a'))
print("10.lstrip of .............hello:","...........welcome".lstrip('.'))
print("11.lower case of string using casefold() method:",str1.casefold())
print("12.isupper:",str1.isupper())
print("13.encoded version of the string:",str1.encode())
print("14.maketrans of 'a' and 'e':",str1.maketrans('a','e'))
print("15.isdicimal:",str1.isdecimal())
print("16.isnumeric:",str1.isnumeric())
print("17.left justify of the string:",str1.ljust(100))
print("18.isspace:",str1.isspace())
print("19.r-partition:",str1.rpartition(' '))
print("20.istitle:",str1.istitle())
print("21.r-split:",str1.rsplit(' '))
print("22.islower:",str1.islower())
print("23.partition:",str1.partition(' '))
print("24.tab size:",str1.expandtabs(4))
print("25.position of last 'a' in the string using find method:",str1.rindex('a'))
print("26.plitline:",str1.splitlines())
print("27.strip:",str1.strip(' '))
print("28.title:",str1.title())
print("29.splitting the string where there is space:",str1.split(' '))
print("30.strip:",str1.strip(' '))
print("31.changing upper case to lower case and vice versa:",str1.swapcase())
print("32.concadenation:","be" + "brave")
print("33.repetition:",str1*3)


